### ISSUE TITLE
v4: using font variants crashes on nodejs

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2959]
E.g., using `mathsf` throws an error on nodejs:

```
Can't load './output/svg/fonts/svg/dynamic/sans-serif': No asyncLoad method specified
.../node_modules/mathjax-full/js/util/Retries.js:25
    var err = new Error('MathJax retry');
              ^

Error: MathJax retry
    at retryAfter (.../node_modules/mathjax-full/js/util/Retries.js:25:15)
    at FontData.getChar (.../node_modules/mathjax-full/js/output/common/FontData.js:580:41)
```

Similarly for `\texttt` etc.

**Comment by dpvc** [comment]
Had the wrong link above, and fixed it, so don't use the one in the email.

**Comment by pkra** [comment]
Oh! Sorry for missing that bit. I never use MathJax via those APIs so I missed it.
