### ISSUE TITLE
v3.2.2 on node: throws an error, "MathJax retry", when I try to convert math with a "prime" symbol

### ISSUE THREAD

**Issue by corinnaSchultz** [mathjax/MathJax#3052]
### Issue Summary

I'm using mathjax 3 for node for the first time. I used to use mathjax-node (which wrapped mathjax v2 so it could be used on node) and now I'm upgrading my node application. I'm not entirely sure I upgraded correctly, so it's possible I'm doing something wrong.

The issue is that when I send a string of mathml that contains an &apos; symbol (intended to be a "prime" like what you use in geometry), mathml throws an error. 

I looked in the code, and it appears that the code's intention is to load an external entity file if mathjax doesn't recognize a character, and waif for it to load. But instead, it throws an error. This seems like a bug to me. I don't see how I can do anything with the error object (which contains a promise) that's thrown.

### Steps to Reproduce:

1. Use this mathML string:
```
<math xmlns="http://www.w3.org/2010/Math/MathML"><semantics><mstyle scriptsizemultiplier="0.87"><msup><mi>A</mi><mo>&apos;</mo></msup><msup><mi>B</mi><mo>&apos;</mo></msup></mstyle><annotation encoding="text/plain"/></semantics></math>
```

3. Pass it into `await htmlDocument.convert(mathML, {})`

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

### Technical details:

* MathJax Version: 3.2.2
* Node 16.13.1

I did the following after looking at the examples linked from the documentation. Let me know if I'm doing something wrong:

```
const {mathjax} = require('mathjax-full/js/mathjax.js')
const {MathML} = require('mathjax-full/js/input/mathml.js')
const {SVG} = require('mathjax-full/js/output/svg.js')
const {liteAdaptor} = require('mathjax-full/js/adaptors/liteAdaptor.js')
const {RegisterHTMLHandler} = require('mathjax-full/js/handlers/html.js')

async function convert (mathML) {
  try {
    const adaptor = liteAdaptor()
    RegisterHTMLHandler(adaptor)

    const htmlDocument = mathjax.document('', {
      InputJax: new MathML(),
      OutputJax: new SVG({
        fontCache: 'none',
      }),
    })

    const node = await htmlDocument.convert(mathML, {})

    return adaptor.innerHTML(node)
  } catch (error) {
    console.log('=====> I threw an error: ', error)
    throw error
  }
}
```

### Supporting information:
This exact same mathML string works fine with mathjax 2.6.1 (wrapped by mathjax-node)

This is the error:
```
Error: MathJax retry
    at retryAfter (/Users/xxxxxxx/node_modules/mathjax-full/ts/util/Retries.ts:99:13)
    at replace (/Users/xxxxxxx/node_modules/mathjax-full/ts/util/Entities.ts:510:17)
```

**Comment by dpvc** [comment]
MathJax sometimes needs to load additional javascript file (for example, when a less-used TeX command is first encountered, it may require loading the code to process that command, or when certain entities are used in MathML input).  Since loading additional code requires the browser to wait for that code to arrive, MathJax has to stop processing the expression until the new code is available.  MathJax uses the "retry" error as a means of stopping the current processing so that it can be restarted when the asynchronous loading of code has completed.  That restarting needs to be handled by code higher-up in the processing chain.

The `htmlDocument.convert()` command you are using is a synchronous function, not an asynchronous one, so it does not trap the retry error itself.  MathJax provides a wrapper function that you can use to wrap the synchronous functions so that they will be retried if there is a need to load other files asynchronously.  So you could use

``` js
const node = await mathjax.handleRetriesFor(() => htmlDocument.convert(mathML, {}));
```

if you want your code to be able to handle the asynchronous actions of MathJax.  If a retry error occurs within the function passed to `handleRetriesFor()`, it will wait for the code that cause the retry to load and then will run the function again, repeating that until no retry occurs, and then return the result.

**Comment by corinnaSchultz** [comment]
ok, thank you. I'll try that.  Is this documented somewhere?

**Comment by dpvc** [comment]
> Is this documented somewhere?

Well, the documentation for the component-based use of MathJax is in pretty good shape, but there is very little for the direct use of the MathJax module files themselves.  The `handleRetriesFor()` function is used in a number of examples (see [here](https://docs.mathjax.org/en/latest/web/webpack.html#the-custom-build-file), [here](https://docs.mathjax.org/en/latest/output/mathml.html), [here](https://mathjax.github.io/MathJax-demos-web/tex-mml.html.html), and [here](https://github.com/mathjax/MathJax-demos-node/blob/d9ba8c61e54683efc04d0e11d5812bc974da65db/speech/mml2svg#L132)).

There is a lot that needs to be done for that documentation.
