### ISSUE TITLE
e.combineWithMathJax error in bundled BetterDiscord plugin

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [mathjax/MathJax#3079]
### Issue Summary

Error happening when trying to import webpack-bundled MathJax inside a BetterDiscord plugin.
Error log: 
```
TypeError: Cannot set property Package of #<Object> which has only a getter
    at a (betterdiscord://plugins/mathjax.plugin.js:9:26745)
    at a (betterdiscord://plugins/mathjax.plugin.js:9:26752)
    at a (betterdiscord://plugins/mathjax.plugin.js:9:26752)
    at a (betterdiscord://plugins/mathjax.plugin.js:9:26752)
    at e.combineWithMathJax (betterdiscord://plugins/mathjax.plugin.js:9:27261)
    at 1585 (betterdiscord://plugins/mathjax.plugin.js:9:251681)
    at __nested_webpack_require_262731__ (betterdiscord://plugins/mathjax.plugin.js:9:255018)
    at eval (betterdiscord://plugins/mathjax.plugin.js:9:256966)
    at eval (betterdiscord://plugins/mathjax.plugin.js:9:258158)
    at 83 (betterdiscord://plugins/mathjax.plugin.js:9:258207)
    at __webpack_require__ (betterdiscord://plugins/mathjax.plugin.js:9:258538)
    at 451 (betterdiscord://plugins/mathjax.plugin.js:9:258244)
    at __webpack_require__ (betterdiscord://plugins/mathjax.plugin.js:9:258538)
    at eval (betterdiscord://plugins/mathjax.plugin.js:9:258869)
    at eval (betterdiscord://plugins/mathjax.plugin.js:9:258895)
    at M.requireAddon (betterdiscord/renderer.js:4:35818)
    at M.loadAddon (betterdiscord/renderer.js:4:8323)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:6315)
```

### Steps to Reproduce:

1. Create necessary files
  - Betterdiscord plugin `src.js`:
```js
import MathJax from 'mathjax';

module.exports = class Plugin {
    start() {
        console.log('Start');
        MathJax.typeset();
    }
}
```

  - Webpack config for bundling `webpack.config.js`:
```js
const path = require('path');

module.exports = {
  entry: './src.js',
  output: {
    filename: 'mathjax.plugin.js',
    path: path.resolve(__dirname, ''),
  },
};
```

  - Bash script for bundling and adding headers `bundle.sh`
```bash
#!/bin/bash

lines_to_append="/**
 * @name MathJaxtTest
 * @author QuantumSoul
 * @description MathJax test
 * @version 0.0.0
 */"
file_path="out/mathjax.plugin.js"

npx webpack --config webpack.config.js

{ echo -e "$lines_to_append"; cat "$file_path"; } > temp_file && mv temp_file "$file_path"
```

2. Install and run
`npm init`
`npm install webpack webpack-cli mathjax`
`./bundle.sh`

3. Add `out/mathjax.plugin.js` to BetterDiscord plugin folder

### Technical details:

* MathJax Version: 3.2
* Client OS: Linux
* Browser: Discord Electron

### Supporting information:

[Here's a folder](https://github.com/BinaryQuantumSoul/discord-latex/tree/main/test-bug) with all files for testing (still need to install discord and better discord)

**Comment by dpvc** [comment]
Your `src.js` doesn't do what I think you want it to do.  Importing or requiring the `mathjax` package sets up MathJax for server-side usage, and exports a single function, `init()` used to pass it a MathJax configuration.  So your `MathJax` import is an object containing that `init()` function, not the `MathJax` global object that has the `typeset()` function.

As the [README](https://github.com/mathjax/MathJax-src#using-mathjax-components-in-node-applications) indicates (in the NOTE at the bottom of that section), this is intended only for server-side node use, not for use in browsers.

For browser use, you could import one of the combined component files, say `tex-chtml.js`, which has no exports, but does set up the global MathJax variable, just as it would in a browser.  Or you could make your own custom build of MathJax as described in the [documentation](https://docs.mathjax.org/en/latest/web/webpack.html#custom-build) that includes the pieces that you need.

MathJax may need to load some components dynamically, which will not be part of your webpacked file, and you will probably need to tell MathJax where those components can be found.  one way to do what would be to use the global `MathJax` variable to provide the configuration before importing the combined component you are using (e.g., put your configuration in a separate .js file and import that first).  Something like

``` js
window.MathJax = {
  loader: {
    paths: {
      mathjax: '<path-to-mathjax-root-directory>'
    }
  }
};
```

The path could be to a CDN that distributes MathJax.  If you use one of the combined components that end in `-full.js`, e.g., `tex-chtml-full.js`, that will reduce the need for dynamically loaded files, but will make a larger payload, as it includes all (or most of) the TeX extensions.

The error message you are getting is probably due to trying to use the server-side setup in the browser.  Try these other approaches and see if they work for you.

**Comment by BinaryQuantumSoul** [comment]
Thank you very much for detailed answer. I'll try soon and tell you if it works

**Comment by BinaryQuantumSoul** [comment]
I still encounter the error using this `src.js`:
```js
import MathJax from 'mathjax/es5/tex-chtml-full';

module.exports = class Plugin {
    start() {
        console.log('Start');
        //MathJax.typeset();
    }
}
```

Error :
```
TypeError: Cannot set property Package of #<Object> which has only a getter
    at a (betterdiscord://plugins/mathjax.plugin.js:10:13839)
    at a (betterdiscord://plugins/mathjax.plugin.js:10:13846)
    at a (betterdiscord://plugins/mathjax.plugin.js:10:13846)
    at a (betterdiscord://plugins/mathjax.plugin.js:10:13846)
    at e.combineWithMathJax (betterdiscord://plugins/mathjax.plugin.js:10:14355)
    at eval (betterdiscord://plugins/mathjax.plugin.js:10:1277167)
    at eval (betterdiscord://plugins/mathjax.plugin.js:10:1301016)
    at 548 (betterdiscord://plugins/mathjax.plugin.js:10:1301020)
    at __webpack_require__ (betterdiscord://plugins/mathjax.plugin.js:10:1301334)
    at 451 (betterdiscord://plugins/mathjax.plugin.js:10:1301051)
    at __webpack_require__ (betterdiscord://plugins/mathjax.plugin.js:10:1301334)
    at eval (betterdiscord://plugins/mathjax.plugin.js:10:1302000)
    at eval (betterdiscord://plugins/mathjax.plugin.js:10:1302026)
    at M.requireAddon (betterdiscord/renderer.js:4:35818)
    at M.loadAddon (betterdiscord/renderer.js:4:8323)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:6315)
```

**Comment by dpvc** [comment]
Your `src.js` file mixes ESM and CommonJS module syntax, and that causes some problems in my tests.  After a half hour of trying, I could not get BetterDiscord to install on Mac OS, so I can't test things in BetterDiscord itself.  But I was able to webpack the file, and load it into both node and a browser to see if it loaded.  

When I use your `src.js`, I get the following error

```
Uncaught Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: 451
```

which is what I would expect from the mixed ESM/CommonJS code.  If I replace the `import` with

``` js
require("mathjax/es5/tex-chtml-full");
```

then the browser loads the plug file (when I include it via `<script src="out/mathjax.plugin.js"></script>`) without errors, and I can run MathJax commands without problem.

Can you try using that `require()` command instead of the import?  I suspect it won't make a difference for you, but it might.  In any case, it seems to be related to how Discord is loading the plugin, and it appears (from your error message) that it may be reading the plugin file and then using `eval()` to run it.  Maybe that is the trigger?

I have seen this error before, and I know that it has to do with processing the configurations, but I have not been able to track down exactly what the setup has to be to trigger it.  Version 4 has a change that avoids the problem, but it is not yet back-ported to v3.  You might try using mathjax@4.0.0-beta.3 and see if that might work avoid the issue.

**Comment by BinaryQuantumSoul** [comment]
Once again, sorry for late reply.
Thank you for taking the time to try and install BetterDiscord, even though you eventually didn't.
I'm lost x)

Here's my new `src.js` using `mathjax@4.0.0-beta.3`
```js
const MathJax = require('mathjax/tex-chtml');

module.exports = class Plugin {
    start() {
        console.log('Start');
        //MathJax.typeset();
    }
}
```
I have this infinite call queue. I also tried `require()` with mathjax3 but still the [same error](https://github.com/mathjax/MathJax/issues/3079#issue-1837752633).
```
RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30151)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
    at Va (betterdiscord://plugins/mathjax.plugin.js:9:30276)
```

**Comment by dpvc** [comment]
Here's another thing to try:  go back to v3, and use

``` javascript
const mjx = require("mathjax/js/components/global.js");

mjx.combineConfig = function (dst, src) {
  for (const id of Object.keys(src)) {
    if (id === '__esModule') continue;
    if (isObject(dst[id]) && isObject(src[id]) &&
        !(src[id] instanceof Promise) /* needed for IE polyfill */) {
      combineConfig(dst[id], src[id]);
    } else if (src[id] !== null && src[id] !== undefined && dst[id] !== src[id]) {
      dst[id] = src[id];
    }
  }
  return dst;
};

const MathJax = require('mathjax/tex-chtml');

module.exports = class Plugin {
    start() {
        console.log('Start');
        //MathJax.typeset();
    }
}
```

for your `src.js` file.  If that doesn't work, add a `console.log("combine")` call at the top of the `combineConfig()` function to make sure that the new function is actually being used, and check the browser console to see if the `combine` message is appearing (it should appear multiple times).

**Comment by BinaryQuantumSoul** [comment]
> ```js
> require("mathjax/js/components/global.js");
> ```

I don't have `js` subfolder in `node_modules/mathjax`. I only have `es5` and there's nothing called `components` nor `global`. Didn't I install properly ? I did `npm install mathjax`.

By the way, I tried the v4 fix but still the same stacktrace.

**Comment by BinaryQuantumSoul** [comment]
I tried a few things and I realized setting an inital config removes the TypeError.
I have `test` followed by `MathJax localStorage error: localStorage is not defined` error in the logs then the plugin fails to load and I have an error saying the plugin doesn't exist.

Using this `src.js`:
 ```js
MathJax = {
    options: {
        enableMenu: false
    },
    tex: {
      inlineMath: [['mthjxinline', 'mthjxinlineend']],
      displayMath: [['mthjxblock', 'mthjxblockend']]
    }
};

require('mathjax-full/es5/tex-chtml');

console.log("test");

module.exports = class Plugin {
    start() {
        console.log('start');
    }
    stop() {
        console.log('stop');
    }
}
```

**Comment by dpvc** [comment]
Sorry for not replying to this earlier.

You might be able to get rid of the `localStorage` issue by adding

``` js
localStorage = {
  getItem() {},
  setItem() {},
  removeItem() {}
}
```

before loading `mathjax-full/es5/tex-chtml`.

I don't know where the `MathJaxTest` error  comes from, as there is no MathJaxTest in the mathjax-full code at all.  Do you have a MathJaxTest anywhere in your code?

**Comment by BinaryQuantumSoul** [comment]
`MathJaxTest` is the name of the plugin.
I was able to have the plugin running using this [webpack tutorial](https://docs.betterdiscord.app/plugins/intermediate/bundling). Here's what my main js file looks like:
```js
Window.MathJax={tex:{inlineMath:[['mthjxinline','mthjxinlineend']],displayMath:[['mthjxblock','mthjxblockend']]}};
Window.localStorage={getItem(){},setItem(){},removeItem(){}};

MathJax = require('mathjax-full/es5/tex-chtml-full');

console.log("test");

export default class Plugin {
    start() {
        console.log('start' );
        MathJax.typeset();
    }
    stop() {
        console.log('stop');
    }
 ```
The problem is that I have an error:
`TypeError: MathJax.typeset is not a function`

**Comment by dpvc** [comment]
> MathJaxTest is the name of the plugin.

Ah, right.  Thanks!

> TypeError: MathJax.typeset is not a function

Remove the `MathJax = ` and just do `require('mathjax-full/es5/tex-chtml-full')`.  That files doesn't export anything, but it does set up the global `MathJax` variable.  if you assign the result of the `require()` to `MathJax`, you will replace the one created by `tex-html-full` with a blank one, leading to your error message.

**Comment by BinaryQuantumSoul** [comment]
Nice, now It finally kinda works xD
(note that I had to change `Window.MathJax=` to  `MathJax=` to remove the `e.combineWithMathJax` error that happened when removing `(const) MathJax =` )

Now I have a smaller problem still related to bundling:
```js

../es5/output/chtml/…MathJax_Zero.woff:1 
 GET https://../es5/output/chtml/fonts/woff-v2/MathJax_Zero.woff net::ERR_NAME_NOT_RESOLVED
../es5/output/chtml/…Main-Regular.woff:1 
 GET https://../es5/output/chtml/fonts/woff-v2/MathJax_Main-Regular.woff net::ERR_NAME_NOT_RESOLVED
../es5/output/chtml/…_Math-Italic.woff:1 
 GET https://../es5/output/chtml/fonts/woff-v2/MathJax_Math-Italic.woff net::ERR_NAME_NOT_RESOLVED
../es5/output/chtml/…_AMS-Regular.woff:1 
 GET https://../es5/output/chtml/fonts/woff-v2/MathJax_AMS-Regular.woff net::ERR_NAME_NOT_RESOLVED
 ```
 I'm using `"mathjax-full": "^3.2.2"` in my `package.json` and my code looks like this:
 ```js
MathJax={tex:{inlineMath:[['mthjxinline','mthjxinlineend']],displayMath:[['mthjxblock','mthjxblockend']]}};
localStorage={getItem(){},setItem(){},removeItem(){}};

require('mathjax-full/es5/tex-chtml-full');

console.log("test");

export default class Plugin {
    start() {
        console.log('start' );
        MathJax.typeset();
    }
    stop() {
        console.log('stop');
    }
}
```

**Comment by BinaryQuantumSoul** [comment]
Fixed with 
`  chtml:{fontURL: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/output/chtml/fonts/woff-v2"}`
Similiar to https://github.com/mathjax/MathJax/issues/2399
Docs can be found [here](https://docs.mathjax.org/en/latest/web/webpack.html?highlight=fontUrl#fonts-for-commonhtml)

**Comment by dpvc** [comment]
Glad you worked that out.  I was going to suggest that, but hadn't had the chance to reply before you found the solution yourself.

**Comment by dpvc** [comment]
> `Windows.MathJax = config`

This should be `window.MathJax` (singular and lowercase).  Try that out and see if that works.  If not, try `global.MathJax`.

Both of these would need to be **before** the `require()` that loads MathJax.  Putting it after would overwrite the MathJax that you have loaded.

**Comment by BinaryQuantumSoul** [comment]
Sorry for Late reply, you change worked!
Thank you :)

**Comment by BinaryQuantumSoul** [comment]
Just a quick update, it's published now https://betterdiscord.app/plugin/LaTeX%20Renderer

**Comment by dpvc** [comment]
Congratulations on publishing your plug-in!
