### ISSUE TITLE
v4 textmacros extension crash

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#3082]
[Here's hoping I didn't (again) overlook an existing open issue.]

Using just `https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.3/tex-mml-chtml.js` (or in my case, a basic nodejs setup), I get a crash for, e.g., `\text{hello}` (or `\(\require{textmacros}  \text{hello}\) ` on the client).

While the error is caught client-side as "Math Input error", the context menu lets me spy `e.getProperty is not a function` which seems to match nodejs where I get

```
TypeError: node.getProperty is not a function
          at Object.getProperty (file:///[snip]/node_modules/mathjax-full/mjs/input/tex/NodeUtil.js:69:21)
          at ParseOptions.addNode (file:///[snip]/node_modules/mathjax-full/mjs/input/tex/ParseOptions.js:51:39)
          at TextParser.copyLists (file:///[snip]/node_modules/mathjax-full/mjs/input/tex/textmacros/TextParser.js:29:30)
          at TextParser.mml (file:///[snip]/node_modules/mathjax-full/mjs/input/tex/textmacros/TextParser.js:19:14)
          at Object.internalMath (file:///[snip]/node_modules/mathjax-full/mjs/input/tex/textmacros/TextMacrosConfiguration.js:40:100)
          at Object.internalMath (file:///[snip]/node_modules/mathjax-full/mjs/input/tex/ParseUtil.js:127:49)
          at BaseMethods.HBox (file:///[snip]/node_modules/mathjax-full/mjs/input/tex/base/BaseMethods.js:654:30)
          at CommandMap.parse (file:///[snip]/node_modules/mathjax-full/mjs/input/tex/SymbolMap.js:108:22)
          at SubHandler.parse (file:///[snip]/node_modules/mathjax-full/mjs/input/tex/MapHandler.js:33:32)
          at TexParser.parse (file:///[snip]/node_modules/mathjax-full/mjs/input/tex/TexParser.js:44:54)
```

**Comment by dpvc** [comment]
> Here's hoping I didn't (again) overlook an existing open issue

Nope, this is a new one.  I can reproduce, and will look into it.

**Comment by pkra** [comment]
Thanks, Davide.

**Comment by dpvc** [comment]
Found it.  It was a bad last-minute edit on my part.  The PR listed above fixes it.

**Comment by dpvc** [comment]
Fixed in v4.0.
