### ISSUE TITLE
Can't load "@mathjax/mathjax-stix2-font/svg.js"

### ISSUE THREAD

**Issue by zhaohm14** [mathjax/MathJax#3138]
I was trying to set specific font in a node server by
```js
require('mathjax').init({
    loader: {
        load: ['input/tex', 'output/svg']
    },
    output: {
        font: 'mathjax-stix2'
    }
}).then((MathJax) => {
    svg = MathJax.tex2svg(latex, {display: true});
    ret = MathJax.startup.adaptor.outerHTML(svg);
    console.log(ret)
}).catch((err) => console.log(err.message));
```

However, this error occurs:
```cmd
i [Error]: Can't load "@mathjax/mathjax-stix2-font/svg.js"
Cannot find package '@mathjax/mathjax-stix2-font' imported from ***/node_modules/mathjax/node-main.js
    at n.failed (***/node_modules/mathjax/node-main.js:1:126886)
    at ***/node_modules/mathjax/node-main.js:1:126376 {
  package: '[mathjax-stix2]/svg'
}
```

The versions of mathjax and mathjax-stix2-font are both @4.0.0-beta.4
```cmd
$ npm list mathjax
mathjax@1.0.0 ***
└── mathjax@4.0.0-beta.4
$ npm list mathjax-stix2-font
mathjax@1.0.0 ***
└── mathjax-stix2-font@4.0.0-beta.4
```

Folder "mathjax" and "mathjax-stix2-font" do exist in "node_modules", and file '***/node_modules/mathjax-stix2-font/svg.js' exists too.
I don't know whether this problem occurs due to my improper operation. I will appreciate it if you can help me with this.
Thanks!

**Comment by dpvc** [comment]
We are planning to go to scoped packages with version 4 of MathJax, and the fonts are set up for that already.  That is why you are seeing the `@mathjax/...` package name.  But the scoped packages aren't yet in place.  You can work around that for now by adding

``` js
        paths: {'mathjax-stix2': 'mathjax-stix2-font'}
``` to the `loader` section of you configuration:

``` js
require('mathjax').init({
    loader: {
        load: ['input/tex', 'output/svg'],
        paths: {'mathjax-stix2': 'mathjax-stix2-font'}
    },
    output: {
        font: 'mathjax-stix2'
    }
})...
```

**Comment by zhaohm14** [comment]
It works. Thanks a lot!
