### ISSUE TITLE
[v4.beta4] unexpected TeX parser crash (regression from beta3)

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#3217]
The following crashes the TeX parser.

```latex
F_{11} \coloneq \mathrm{Hensel\_qf\_unimodular}(F_{11}, p^{-i_1} G_1, p^{-i_1} Z_{11}', a,b)
```

This appears to be a regression from v4.beta3.

Minimal example: `\mathrm{a\_b}`.

```
/node_modules/mathjax-full/mjs/input/tex/TexParser.js:328
                node.childNodes[1].attributes.set(TexConstant.Attr.LATEX, str);
                                   ^

TypeError: Cannot read properties of undefined (reading 'attributes')
    at TexParser.updateResult (/node_modules/mathjax-full/mjs/input/tex/TexParser.js:328:36)
    at TexParser.parse (/node_modules/mathjax-full/mjs/input/tex/TexParser.js:51:14)
    at TexParser.Parse (/node_modules/mathjax-full/mjs/input/tex/TexParser.js:74:18)
    at new TexParser (/node_modules/mathjax-full/mjs/input/tex/TexParser.js:27:14)
    at BaseMethods.MathFont (/node_modules/mathjax-full/mjs/input/tex/base/BaseMethods.js:165:15)
    at CommandMap.parse (/node_modules/mathjax-full/mjs/input/tex/TokenMap.js:108:22)
    at SubHandler.parse (/node_modules/mathjax-full/mjs/input/tex/MapHandler.js:33:32)
    at TexParser.parse (/node_modules/mathjax-full/mjs/input/tex/TexParser.js:50:60)
    at controlSequence (/node_modules/mathjax-full/mjs/input/tex/ParseMethods.js:45:16)
    at RegExpMap.parse (/node_modules/mathjax-full/mjs/input/tex/TokenMap.js:21:49)

Node.js v21.7.1
```

**Comment by pkra** [comment]
`mathop` runs into the same problem, it seems. But `\text{}` seems to workaround it at least.

**Comment by dpvc** [comment]
This is a duplicate of #3120 where you reported that earlier.  It is the `\_`, as you have noted, and is fixed in mathjax/MathJax#1028.

**Comment by pkra** [comment]
Ah, sorry for the noise :disappointed:

**Comment by dpvc** [comment]
No problem.
