### ISSUE TITLE
bussproofs boundary not correctly computed

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [mathjax/MathJax#3240]
**Replace the text below with the details of the issue you are facing.  
DO NOT simply erase the form and type a free-form response.**
-----

### Issue Summary

I am using Math Jax 3 with bussproofs. Boundaries of the SVG box 
are not correctly computed leading to problems like uncorrect page 
width centering and missing horizontal scroll bar. The problem
is observable for example in the Chrome browser.

### Steps to Reproduce:

1. Use Math Jax 3 with bussproofs:

beginning of the HTML document:
```
<script>
    window.MathJax = {
        loader: {load: ['[tex]/bussproofs']},
        tex: {packages: {'[+]': ['bussproofs']}}
    };
</script>
```
end of the HTML document:
```
<script type="text/javascript" id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
</script>
```
JavaScript call when the plain content has been rendered:
```
   MathJax.typeset();
```

2. This is the second step
Create a small example:
```
\begin{prooftree}\AxiomC{}
\RightLabel{Ax}\UnaryInfC{p ⊢ p}
\RightLabel{I→}\UnaryInfC{ ⊢ p → p}
\end{prooftree}
```
Create a larger example:
```
\begin{prooftree}\AxiomC{}
\RightLabel{Ax}\UnaryInfC{p ⊢ p}
\AxiomC{}
\RightLabel{Ax}\UnaryInfC{¬p ⊢ ¬p}
\RightLabel{E→}\BinaryInfC{¬p, p ⊢ ⊥}
\RightLabel{I→}\UnaryInfC{¬p, p ⊢ ¬ ¬q}
\RightLabel{DNE}\UnaryInfC{¬p, p ⊢ q}
\RightLabel{I→}\UnaryInfC{¬p ⊢ p → q}
\AxiomC{}
\RightLabel{Ax}\UnaryInfC{(p → q) → p ⊢ (p → q) → p}
\RightLabel{E→}\BinaryInfC{(p → q) → p, ¬p ⊢ p}
\AxiomC{}
\RightLabel{Ax}\UnaryInfC{p ⊢ p}
\AxiomC{}
\RightLabel{Ax}\UnaryInfC{¬p ⊢ ¬p}
\RightLabel{E→}\BinaryInfC{¬p, p ⊢ ⊥}
\RightLabel{I→}\UnaryInfC{¬p ⊢ ¬p}
\RightLabel{E→}\BinaryInfC{¬p, (p → q) → p ⊢ ⊥}
\RightLabel{I→}\UnaryInfC{(p → q) → p ⊢ ¬ ¬p}
\RightLabel{DNE}\UnaryInfC{(p → q) → p ⊢ p}
\RightLabel{I→}\UnaryInfC{ ⊢ ((p → q) → p) → p}
\end{prooftree}
```
3. Further steps, etc.
The smaller example has an Ok bounding box:

![small](https://github.com/mathjax/MathJax/assets/95891213/691d54bf-d5b8-4b29-a4bf-86e674cd60f5)

The larger example has  a not Ok bounding box:

![large](https://github.com/mathjax/MathJax/assets/95891213/3a7de4dc-5e77-4021-91c4-047291795940)

### Technical details:

See intro and steps.

### Supporting information:

You can try it online:
https://www.xlog.ch/runtab/doclet/docs/06_demo/wilson/example42/package.html

**Comment by Jean-Luc-Picard-2021** [comment]
I suspect it has to do with the kerning of the Unicode code 
points I was using. I find a similar problem else where 
where a kerning problem with Unicode is better seen.

**Comment by dpvc** [comment]
Your "kerning" issue is actually a different problem.  It is a bug in the v3 SVG output when characters are used that aren't in the default MathJax TeX fonts.  In this case, it is because upright Greek letters are not in the MathJax TeX fonts, and so that is triggering the bug.  The bug is fixed in v4 (currently out in beta release).  If you control the website that is displaying the results, you could switch to that.  But if you are using a website like the one you link to for the example at the bottom of your original post, then your only choice to deal with the "kerning" problem is to switch to CHTML output using the MathJax contextual menu.

The centering/scroll-bar problem you originally reported is a different problem, however.  The bussproofs macros are not correctly computing the full width of the expression, and are leaving the width giving the incorrect bounding box in your image above.  I do not currently have a work-around for that.  We will have to look into it further.

**Comment by zorkow** [comment]
As @dpvc mentioned, the issue you are seeing is that we are working with a lot of negative spacing to compute the size of the inference bars and centering of conclusions. This has an effect on the bounding boxes that are generally assumed to be smaller than the actual element they contains.

There are some improvements around bounding box computation in version 4. While they are not specific to bussproofs, they might still be helpful for you. Please give it a go.

E.g., here is a difference between bounding boxes I can observe between MJ3 and MJ4 in the a11y explorer. Let me know if switching to MJ4 does make a difference for you.

![Screenshot from 2024-06-12 16-24-14](https://github.com/mathjax/MathJax/assets/5717215/5ac44349-397a-4c6c-97c2-05a7fd65164e)
![Screenshot from 2024-06-12 16-25-30](https://github.com/mathjax/MathJax/assets/5717215/299f364a-f901-4c42-a584-0a4c47f3bbc8)

**Comment by Jean-Luc-Picard-2021** [comment]
Would it be adviseable to split off the Unicode kerning problem,
into a separate ticket from the bounding box problem?

P.S.: I didn't have time yet to test V4 or CHTML.

**Comment by dpvc** [comment]
> Would it be adviseable to split off the Unicode kerning problem, into a separate ticket from the bounding box problem?

Not at this point.  That is already resolved in v4.  Once that is released, we will look into back-porting some bug fixes like this, but there is not need to make a new issue at this point.

**Comment by Jean-Luc-Picard-2021** [comment]
I tried CHTML. It shows an error message as soon as I use
non-Latin. Characters, for example the greek λ and μ. So I
cannot test CHTML and the Unicode Kerning problem.

This is CHTML without Greek:

![image](https://github.com/mathjax/MathJax/assets/95891213/8dae73cb-8aba-4fde-9a61-c99dadfea3a3)

This is CHTML with Greek:

![image](https://github.com/mathjax/MathJax/assets/95891213/76d8f235-13f4-4d40-9d37-db2c9011706c)

On the other hand SVG shows the Greek:

![image](https://github.com/mathjax/MathJax/assets/95891213/9a99332e-f017-4a92-95dd-058a2aeb42c0)

**Comment by dpvc** [comment]
OK, here's what's happening.  The buss proofs macros need to figure out the size of the various pieces so that they can be properly placed, and that means they have to call the output renderer to ask it to determine how big they are.  That is done by a `MathItem` that contains the expression to be measured and asking the output renderer to get its bounding box.  The `Mathitem` also contains information about where the expression is within the document's DOM, but in this case, it is not hooked into the DOM, so those pointers are `null`.  When the renderer tries to get the bounding box, it adds up all the bounding boxes for the characters in the expression and returns that, but if a character is not in its fonts, it tries to measure the width by putting it into a DOM element and measuring the width of that.  That DOM element is supposed to be put into the same container as the expression itself, so that it has the same CSS affecting it, but in the case of this detached `MathItem`, there is not parent DOM item, and that causes the error message you are seeing (about the parent being `null`).

There are several possible work-arounds.  One is to use

``` js
MathJax = {
  startup: {
    ready() {
      MathJax.startup.defaultReady();
      const jax = MathJax.startup.document.outputJax;
      Object.assign(jax, {
        _measureTextNode_: jax.measureTextNode,
        measureTextNode: function (textNode) {
          return (!this.math.start.node ? {w: .67, h: .75, d: .2} : this._measureTextNode_(node))
        }
      });
    }
  }
};
```

This checks if the `MathItem` has a DOM node and if not, it returns a generic bounding box (so just an approximation), otherwise it does its usual measuring.  This will prevent the error, but may not get the spacing exactly right.

The other approach is to make sure that you only use characters that are in the MathJax fonts.  In v4, the character coverage is much greater, but in v3, there are no upright Greek lower-case letters like the ones you are using, and that does trigger the problem described above.  But you *could* use something like

``` latex
\RightLabel{Ax}\UnaryInfC{$\phi$ ⊢ $\phi$}
```

to get the italic phi character that MathJax has.  Or even

``` latex
\RightLabel{Ax}\UnaryInfC{$\phi \vdash \phi$}
```

Of course, if you already have a lot of content, it might not be easy to change them.  In that case, you could use

``` js
MathJax = {
  startup: {
    ready() {
      MathJax.startup.defaultReady();
      document.getElementById('render').disabled = false;
      MathJax.startup.document.inputJax[0].preFilters.add(({math}) => {
        math.math = math.math
                     .replace(/\u03C6/g, '$\\phi$')   // or \varphi if that is better
                     .replace(/\u03C7/g, '$\\chi$')
                     .replace(/\u03C8/g, '$\\psi$');
      });
    }
  }
};
```

 in order have the Unicode characters mapped to the corresponding TeX macros in math mode.  You could add other replacements as needed.  For example, you could map `x1` to `$x_1$` or `$\mathrm{x}_1$`, if you like.  But if you are using these characters in other expressions on your page, you might have to be more careful about the replacements, as these are being applied to every expression on the page.  In that case, it might be best search for `\begin{prooftree}...\end{prooftree}` and then do the replacement on its contents.  Let me know if you need that instead.

With this configuration, your example from your second post above (the only one I had the source for) would produce

<img width="825" alt="proof" src="https://github.com/mathjax/MathJax/assets/432782/5f76acf7-9039-498e-880a-f68086331d58">

**Comment by Jean-Luc-Picard-2021** [comment]
Now I have an example where the box is extremly off, and
Unicode is not involved. The error somehow accumulates with
the size of the proof:

![image](https://github.com/mathjax/MathJax/assets/95891213/230c7669-50b3-4bc3-9ad8-350a0a96ecc6)

**Comment by dpvc** [comment]
The original issue of the bounding box for the proof being incorrect is resolved in the pull request linked above.

**Comment by Jean-Luc-Picard-2021** [comment]
Sounds good! Will do some testing soon...

**Comment by dpvc** [comment]
The fix has been merged into the `develop` branch.

**Comment by Jean-Luc-Picard-2021** [comment]
Is the develop v4 branch different from the v3 in
terms of the API to use MathJax? Somehow I cannot test it.
With the test case as documented at the beginning of this

issue. I only changed the end of  the HTML document 
to this here:
```
<script type="text/javascript" id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.3/tex-chtml.js">
</script>
```
The rest is the same in that Math.typeset() is called after 
the output was generated. I then get this error:
```
Error: MathJax retry
    at Object.Mn [as retryAfter] (tex-chtml.js:1:125320)
    at Dn.enrich (tex-chtml.js:1:864349)
    at t.enrich (tex-chtml.js:1:866205)
    at Object.renderDoc (tex-chtml.js:1:114661)
    at pn.renderDoc (tex-chtml.js:1:114773)
    at t.render (tex-chtml.js:1:116221)
    at Ei.typeset (tex-chtml.js:1:33587)
    at HTMLButtonElement.main_async (package.html?_ijt=o229alrkvl53hc6r7d53l241nr&_ij_reload=RELOAD_ON_SAVE:78:25)
````
And output is not rendered:

![image](https://github.com/mathjax/MathJax/assets/95891213/8ea66157-fee6-4790-b008-e5fc0893265f)

**Comment by dpvc** [comment]
The `retry` error is part of MathJax's internal mechanism for handling dynamically loaded code.  When you see this error, it means you need to be using the promise-based calls in order to handle the asynchronous loading of some piece of MathJax code.  Since you are using `MathJax.typeset()`, which is the synchronous call that doesn't handle dynamic code, you need to switch to `MathJax.typesetPromise()` and deal with the promises that allow the handling of asynchronous loading of code.

The reason you are getting that in v4 but didn't in v3 is because v4 introduced new fonts that have much larger glyph coverage, and the font data is now broken into multiple smaller pieces to reduce the initial download and only loads some character data as it is needed.  That means the output rendering can be asynchronous where it wasn't in v3.  See the [release notes for the alpha release](https://github.com/mathjax/MathJax-src/releases/tag/4.0.0-alpha.1#promises) for more details.

You should be able to use the new bussproofs extension with v3 (though you will get a console warning about version mismatches).
